"""Initial developer-created modules for the fresh Modular Orbit app."""

from __future__ import annotations

from app.modules.contracts import FrontendBlock, ModuleDefinition, RetrievalPolicy


INITIAL_MODULES: tuple[ModuleDefinition, ...] = (
    ModuleDefinition(
        module_id="curious",
        name="Curious",
        description="Asks structured questions to understand the person and populate the User Model.",
        roles=("capture", "output", "query"),
        storage_strategy="generalized",
        valid_lifecycle_statuses=("active", "completed", "archived", "deleted"),
        retrieval_policy=RetrievalPolicy(
            mode="summary",
            chunk_source=("payload.question_text", "payload.response"),
            min_signal="always",
            delete_behavior="delete",
            create_chunks=True,
            create_bucket_updates=True,
            default_chunk_status="pending",
            notes="Curious answers always create summary chunks and direct Bucket Updates for their target Story Bucket.",
        ),
        suggestion_threshold=None,
        item_chat_enabled=True,
        item_chat_system_prompt=(
            "Help the person reflect on this answer. Ask whether it still feels true. "
            "If they want to revise or elaborate, keep it tied to the same Story Bucket."
        ),
        frontend_blocks=(
            FrontendBlock(
                block_id="curious_prompt",
                name="Curious Prompt",
                size="medium",
                description="Shows onboarding or one high-value gap question.",
            ),
        ),
        default_settings={
            "onboarding_required": True,
            "notify_questions_enabled": True,
            "max_new_questions_per_week": 3,
            "curious_paused": False,
            "gap_max_questions_per_day": 1,
            "dismissed_question_cooldown_days": 7,
            "suggestions_enabled": False,
            "companion_enabled": True,
            "companion_persona_preset": "warm",
            "companion_persona_override": "",
            "companion_checkins_per_day": 0,
        },
    ),
    ModuleDefinition(
        module_id="logs",
        name="Logs",
        description="Timestamped personal observations, updates, and lightweight life events.",
        roles=("capture", "query", "dashboard"),
        storage_strategy="generalized",
        valid_lifecycle_statuses=("active", "archived", "deleted"),
        retrieval_policy=RetrievalPolicy(
            mode="selective",
            chunk_source=("title", "description", "payload.text", "payload.occurred_at"),
            min_signal="meaningful_only",
            delete_behavior="delete",
            create_chunks=True,
            create_bucket_updates=True,
            default_chunk_status="pending",
            notes="Logs are often useful signal, but are not completable work.",
        ),
        suggestion_threshold=0.85,
        item_chat_enabled=True,
        item_chat_system_prompt="Discuss the log as observed evidence, not as a task unless the person asks to convert it.",
        frontend_blocks=(
            FrontendBlock(
                block_id="recent_logs",
                name="Recent Logs",
                size="medium",
                description="Shows the latest captured logs.",
            ),
        ),
        default_settings={
            "bucket_updates_enabled": True,
            "meaningfulness_threshold": "medium",
        },
    ),
    ModuleDefinition(
        module_id="tasks",
        name="Tasks",
        description="Actionable work the person may complete, archive, or delete.",
        roles=("capture", "query", "dashboard"),
        storage_strategy="extended",
        valid_lifecycle_statuses=("active", "completed", "archived", "deleted"),
        retrieval_policy=RetrievalPolicy(
            mode="summary",
            chunk_source=("title", "description", "payload.due_date", "payload.priority", "payload.module_status"),
            min_signal="meaningful_only",
            delete_behavior="delete",
            create_chunks=False,
            create_bucket_updates=True,
            default_chunk_status="not_needed",
            notes="Task exact fields live in task_items; chunks are created only when task context is meaningful.",
        ),
        suggestion_threshold=0.9,
        item_chat_enabled=True,
        item_chat_system_prompt="Keep the discussion action-oriented: clarify next steps, blockers, due dates, and tradeoffs.",
        frontend_blocks=(
            FrontendBlock(
                block_id="task_list",
                name="Task List",
                size="large",
                description="Lists active and recently completed tasks.",
            ),
        ),
        default_settings={
            "default_priority": None,
            "show_completed_days": 7,
        },
        side_table="task_items",
        side_table_rationale="Tasks need exact due-date, priority, completion, and status queries.",
    ),
    ModuleDefinition(
        module_id="plans",
        name="Plans",
        description="Structured multi-step intentions with progress tracking.",
        roles=("capture", "query", "dashboard"),
        storage_strategy="extended",
        valid_lifecycle_statuses=("active", "completed", "archived", "deleted"),
        retrieval_policy=RetrievalPolicy(
            mode="summary",
            chunk_source=("title", "description", "payload.steps", "payload.progress_percent"),
            min_signal="always",
            delete_behavior="delete",
            create_chunks=True,
            create_bucket_updates=True,
            default_chunk_status="pending",
            notes="Plan summaries are retrievable while exact progress lives in Side Tables.",
        ),
        suggestion_threshold=0.9,
        item_chat_enabled=True,
        item_chat_system_prompt="Discuss plan progress, sequencing, blockers, and next actions.",
        frontend_blocks=(
            FrontendBlock(
                block_id="plan_progress",
                name="Plan Progress",
                size="large",
                description="Shows active plans and progress.",
            ),
        ),
        default_settings={
            "show_completed_days": 14,
        },
        side_table="plan_items",
        side_table_rationale="Plans need exact progress, step, and completion queries.",
    ),
    ModuleDefinition(
        module_id="goals",
        name="Goals",
        description="Stable goal entries stored in goals.md with IDs that Connections can target.",
        roles=("query",),
        storage_strategy="generalized",
        valid_lifecycle_statuses=("active", "archived", "deleted"),
        retrieval_policy=RetrievalPolicy(
            mode="none",
            chunk_source=(),
            min_signal="confirmed_only",
            delete_behavior="delete",
            create_chunks=False,
            create_bucket_updates=False,
            default_chunk_status="not_needed",
            notes="Goals are read from structured markdown and targeted by stable goal IDs.",
        ),
        suggestion_threshold=0.85,
        item_chat_enabled=False,
        frontend_blocks=(),
        default_settings={
            "active_section": "Active",
            "tentative_section": "Tentative",
        },
    ),
    ModuleDefinition(
        module_id="chat",
        name="Chat",
        description="Conversation surfaces for free chat, context chat, decision mode, and Item Chat.",
        roles=("query", "output"),
        storage_strategy="generalized",
        valid_lifecycle_statuses=("active", "archived", "deleted"),
        retrieval_policy=RetrievalPolicy(
            mode="none",
            chunk_source=(),
            min_signal="confirmed_only",
            delete_behavior="delete",
            create_chunks=False,
            create_bucket_updates=False,
            default_chunk_status="not_needed",
            notes="Free chat is not ingested as Life Items unless the person confirms a Capture Proposal.",
        ),
        suggestion_threshold=0.9,
        item_chat_enabled=False,
        frontend_blocks=(),
        default_settings={
            "default_mode": "standard",
            "max_suggestions_per_session": 2,
        },
    ),
    ModuleDefinition(
        module_id="documents",
        name="Documents",
        description="Uploaded files and notes that can produce document-level meaning and retrievable chunks.",
        roles=("capture", "query", "dashboard", "external_intake"),
        storage_strategy="extended",
        valid_lifecycle_statuses=("active", "archived", "deleted"),
        retrieval_policy=RetrievalPolicy(
            mode="full_text",
            chunk_source=("uploaded_text",),
            min_signal="always",
            delete_behavior="delete",
            create_chunks=True,
            create_bucket_updates=True,
            default_chunk_status="pending",
            notes="Documents use document-level Connection Notes plus chunks for retrieval.",
        ),
        suggestion_threshold=0.9,
        item_chat_enabled=True,
        item_chat_system_prompt="Discuss the document as a coherent source before drilling into chunks.",
        frontend_blocks=(
            FrontendBlock(
                block_id="document_library",
                name="Document Library",
                size="large",
                description="Shows uploaded documents and their connection status.",
            ),
        ),
        default_settings={
            "unique_name_editable": True,
            "chunking_enabled": True,
        },
        side_table="document_items",
        side_table_rationale="Documents need globally unique names and exact metadata lookup.",
    ),
    ModuleDefinition(
        module_id="user_model",
        name="User Model",
        description="Editable Story Buckets that represent what Orbit understands about the person.",
        roles=("query",),
        storage_strategy="generalized",
        valid_lifecycle_statuses=("active", "archived", "deleted"),
        retrieval_policy=RetrievalPolicy(
            mode="none",
            chunk_source=(),
            min_signal="confirmed_only",
            delete_behavior="delete",
            create_chunks=False,
            create_bucket_updates=False,
            default_chunk_status="not_needed",
            notes="User Model data lives in Story Buckets and is edited through dedicated endpoints.",
        ),
        suggestion_threshold=0.95,
        item_chat_enabled=False,
        frontend_blocks=(),
        default_settings={},
    ),
    ModuleDefinition(
        module_id="recommendations",
        name="Recommendations",
        description="Generated suggestions that draw from existing life data and are saved only after confirmation.",
        roles=("output", "query", "dashboard"),
        storage_strategy="generalized",
        valid_lifecycle_statuses=("active", "archived", "deleted"),
        retrieval_policy=RetrievalPolicy(
            mode="summary",
            chunk_source=("title", "description", "payload"),
            min_signal="confirmed_only",
            delete_behavior="delete",
            create_chunks=True,
            create_bucket_updates=False,
            default_chunk_status="pending",
            notes="Recommendations are stored only after acceptance.",
        ),
        suggestion_threshold=0.95,
        item_chat_enabled=True,
        item_chat_system_prompt="Discuss recommendation rationale, assumptions, and alternatives.",
        frontend_blocks=(
            FrontendBlock(
                block_id="recent_recommendations",
                name="Recent Recommendations",
                size="medium",
                description="Shows accepted recommendations.",
            ),
        ),
        default_settings={
            "save_requires_confirmation": True,
            "max_options": 3,
        },
    ),
    ModuleDefinition(
        module_id="strategies",
        name="Strategies",
        description="Generated approaches for allocating attention, sequencing work, and making tradeoffs.",
        roles=("output", "query", "dashboard"),
        storage_strategy="generalized",
        valid_lifecycle_statuses=("active", "completed", "archived", "deleted"),
        retrieval_policy=RetrievalPolicy(
            mode="summary",
            chunk_source=("title", "description", "payload"),
            min_signal="confirmed_only",
            delete_behavior="delete",
            create_chunks=True,
            create_bucket_updates=True,
            default_chunk_status="pending",
            notes="Strategies can become Life Items after acceptance.",
        ),
        suggestion_threshold=0.95,
        item_chat_enabled=True,
        item_chat_system_prompt="Discuss tradeoffs, time allocation, risks, and goal fit.",
        frontend_blocks=(
            FrontendBlock(
                block_id="active_strategies",
                name="Active Strategies",
                size="large",
                description="Shows accepted active strategies.",
            ),
        ),
        default_settings={
            "save_requires_confirmation": True,
            "default_time_horizon": "weekly",
        },
    ),
)
